[package]
name = "attain-bigquery-client"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
anyhow = "1.0"
serde_json = "1.0"
async-trait = "0.1"
dirs = "5.0"
toml = "0.8"
configparser = "3.1.0"